In [58]:
import pandas as pd
import numpy as np

In [ ]:
series = pd.Series(5, index=[0,0,3,4,5])
series

0    5
0    5
3    5
4    5
5    5
dtype: int64

In [4]:
series1= pd.Series(list("abc"))
series1

0    a
1    b
2    c
dtype: object

In [6]:
# series = pd.Series({"a":[10,20],"b":np.random.randn(3),"c":30})
series= pd.Series({
    'a': [10, 20],
    'b': 'a',
    'c': np.random.randn(3, 3)
})
series

a                                             [10, 20]
b                                                    a
c    [[-1.8945928560424625, -1.4050233291807028, 1....
dtype: object

In [12]:
print(series['a'])
print(series[0])

[10, 20]
[10, 20]

C:\Users\singh\AppData\Local\Temp\ipykernel_1204\2223819552.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[0])

In [6]:
print(series.iloc[0])
print(series.loc['a'])

[10, 20]
[10, 20]

In [ ]:
print(series[:3])
# print(series[:3,:]) multi- index error

a                                             [10, 20]
b                                                    a
c    [[-1.8945928560424625, -1.4050233291807028, 1....
dtype: object

KeyError: 'key of type tuple not found and not a MultiIndex'

In [ ]:
print(series.loc[:"c"])
print(series.iloc[1:3:2])

a                                             [10, 20]
b                                                    a
c    [[-1.8945928560424625, -1.4050233291807028, 1....
dtype: object
b    a
dtype: object

In [57]:
s=pd.Series(np.random.randn(5),index=["a","b","c","d","e"])
print("series:\n",s)
print("median: ",s.median())
print(s>s.median())
s[s>s.median()]

series:
 a    0.081074
b    0.020714
c    0.114858
d    0.911037
e   -0.182937
dtype: float64
median:  0.0810744824146967
a    False
b    False
c     True
d     True
e    False
dtype: bool

c    0.114858
d    0.911037
dtype: float64

In [ ]:
np.exp(s)
# return e pow s: e= 2.71

a    0.598387
b    1.098000
c    1.374610
d    0.851150
e    0.716820
dtype: float64

In [20]:
s

a   -0.513517
b    0.093490
c    0.318170
d   -0.161167
e   -0.332931
dtype: float64

In [56]:
print(s['a'])
print(s.loc['a'])
s.get("f",5)
# if present returns value at index else default 5

-0.5348730394601079
-0.5348730394601079

5

In [23]:
s+s

a    2.475119
b   -5.902478
c    1.905768
d   -1.671928
e   -1.447178
dtype: float64

In [24]:
s*2

a    2.475119
b   -5.902478
c    1.905768
d   -1.671928
e   -1.447178
dtype: float64

In [25]:
s*s

a    1.531553
b    8.709811
c    0.907988
d    0.698836
e    0.523581
dtype: float64

In [ ]:
print(s.iloc[:-1])
# print(s.iloc[1:]+s.iloc[:-1])
(s.iloc[1:]+ s.iloc[:-1]).dropna()

a   -0.513517
b    0.093490
c    0.318170
d   -0.161167
dtype: float64

b    0.186980
c    0.636339
d   -0.322335
dtype: float64

In [ ]:
# series= pd.Series({
#     'a': 'ab',
#     'b': 'd'
# })
# series.loc['c']= series['a']+ series['b']
# series
series= pd.Series({
    'a': 'ab',
    'b': 'd',
    'c': 'ms',
    'd': 'd'
})
series1= series.loc['b':]+ series.iloc[:-1]
series1

b     d
c    ms
d     d
dtype: object

a     NaN
b      dd
c    msms
d     NaN
dtype: object

In [68]:
s=pd.Series(np.random.randn(4),name="something")
print(s.name)
s

something

0   -1.182688
1   -0.485070
2    1.025110
3    0.644079
Name: something, dtype: float64

In [66]:
s.name="different"
s

0    1.066828
1   -0.315376
2   -0.120087
3    0.287755
Name: different, dtype: float64

In [69]:
# s2=s.rename("some", inplace= True)
s2= s.rename("diff")
print(s2)
print(s)

0   -1.182688
1   -0.485070
2    1.025110
3    0.644079
Name: diff, dtype: float64
0   -1.182688
1   -0.485070
2    1.025110
3    0.644079
Name: something, dtype: float64

In [ ]:
d={
    "one":pd.Series(list(range(1,4)),index=list("abc")),
    "two":pd.Series(list(range(1,5)),index=list("abcd"))
}
df=pd.DataFrame(d)
# Remember here you are providing values as pd.Series so unequal values works else throws ValueError
# this only happens when all the values are of pd.Series and no list
df

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [71]:
# new Series/DataFrame from existing ones with alterations
print(pd.Series(s))
pd.DataFrame(df, index= list("bad"))
# pd.DataFrame(df, index= list("bad"), columns=['one','2'])
    # creates new col or index

0   -1.182688
1   -0.485070
2    1.025110
3    0.644079
Name: something, dtype: float64

   one  two
b  2.0    2
a  1.0    1
d  NaN    4

In [37]:
type(df.loc["b","two"])

numpy.int64

In [34]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [51]:
df.columns

Index(['one', 'two'], dtype='object')

In [75]:
# data = np.zeros((2,), dtype=[("A","i4"),("B","f4"),("C","S10"), ("D","S10")])
data = np.zeros((2,), dtype=[("A","i4"),("B","f4"),("C","S10")])
print(data)
# data=[(1,2,"hello"),(2,3.0,"world")]
# data[:]=[(1,2,"hello"),(2,3.0,"world"),(2,3.0,"world")]
# doesn't work
data[:]=[(1,2,"hello"),(2,3.0,"world")]
pd.DataFrame(data)

[(0, 0., b'') (0, 0., b'')]

   A    B         C
0  1  2.0  b'hello'
1  2  3.0  b'world'

In [60]:
data={
        "a":[10,20],
        "b":10}
pd.DataFrame(data)

    a   b
0  10  10
1  20  10